### ISSUE TITLE
[Question] Setters on properties

### ISSUE THREAD

**Issue by joseffilzmaier** [Wifx/gonetworkmanager#9]
Hello!

There are a lot of getters for almost all properties of NetworkManager. But there are almost no setters.
In my case i would need the property to set a device managed or unmanaged.
Is this a design decision to not include setters or simply a lack of time?

Would you take pull requests if i provide the patches in the latter case?

Greetings

**Comment by mullerch** [comment]
Hello,
Of course new content is welcome! This library is developed by the community. Generally speaking only what is used by someone is developed. That said, I've added all the constant for the paths so that we have an overview. The first setter has just been added recently in [98840bd76a190b6d482ee8bd01ff2bf853eb1c53].

**Comment by joseffilzmaier** [comment]
That's nice to hear!
I've created a pull request #10 - Could you please review and comment or merge?

Greetings
